[package]
default-run = "reth"
description = "Reth node implementation"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "reth"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-auto-seal-consensus.workspace = true
reth-basic-payload-builder.workspace = true
reth-beacon-consensus.workspace = true
reth-blockchain-tree.workspace = true
reth-config.workspace = true
reth-consensus-common.workspace = true
reth-db = {workspace = true, features = ["mdbx"]}
reth-discv4.workspace = true
reth-downloaders.workspace = true
reth-ethereum-payload-builder.workspace = true
reth-interfaces = {workspace = true, features = ["clap"]}
reth-network = {workspace = true, features = ["serde"]}
reth-network-api.workspace = true
reth-static-file = { workspace = true, features = ["clap"] }
reth-trie = { workspace = true, features = ["metrics"] }
reth-nippy-jar.workspace = true
reth-node-api.workspace = true
reth-node-core.workspace = true
reth-node-builder.workspace = true
reth-node-ethereum.workspace = true
reth-node-optimism = {workspace = true, optional = true, features = [
  "optimism",
]}
reth-optimism-payload-builder = {workspace = true, optional = true}
reth-payload-builder.workspace = true
reth-payload-validator.workspace = true
reth-primitives = {workspace = true, features = ["arbitrary", "clap"]}
reth-provider = {workspace = true}
reth-prune.workspace = true
reth-revm.workspace = true
reth-rpc-api = {workspace = true, features = ["client"]}
reth-rpc-builder.workspace = true
reth-rpc-engine-api.workspace = true
reth-rpc-types-compat.workspace = true
reth-rpc-types.workspace = true
reth-rpc.workspace = true
reth-stages.workspace = true
reth-tasks.workspace = true
reth-tracing.workspace = true
reth-transaction-pool.workspace = true

# crypto
alloy-chains.workspace = true
alloy-rlp.workspace = true

# tracing
tracing.workspace = true

# io
confy.workspace = true
fdlimit = "0.3.0"
serde.workspace = true
serde_json.workspace = true
toml = {workspace = true, features = ["display"]}

# metrics
metrics-process = "=1.0.14"

# test vectors generation
proptest.workspace = true
rand.workspace = true

# tui
comfy-table = "7.0"
crossterm = "0.27.0"
human_bytes = "0.4.1"
ratatui = "0.25.0"

# async
futures.workspace = true
tokio = {workspace = true, features = [
  "sync",
  "macros",
  "time",
  "rt-multi-thread",
]}

# misc
aquamarine.workspace = true
boyer-moore-magiclen = "0.2.16"
eyre.workspace = true
clap = { workspace = true, features = ["derive"] }
backon = "0.4"
itertools.workspace = true
rayon.workspace = true
similar-asserts.workspace = true
tempfile.workspace = true
thiserror.workspace = true

[target.'cfg(not(windows))'.dependencies]
jemallocator = {version = "0.5.0", optional = true}

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
assert_matches = "1.5.0"
jsonrpsee.workspace = true

[features]
# default = ["jemalloc"]
##------LUMIO-START-------
default = ["jemalloc", "optimism"]
##------LUMIO-END---------

asm-keccak = ["reth-primitives/asm-keccak"]

jemalloc = ["dep:jemallocator", "reth-node-core/jemalloc"]
jemalloc-prof = ["jemalloc", "jemallocator?/profiling"]

min-debug-logs = ["tracing/release_max_level_debug"]
min-error-logs = ["tracing/release_max_level_error"]
min-info-logs = ["tracing/release_max_level_info"]
min-trace-logs = ["tracing/release_max_level_trace"]
min-warn-logs = ["tracing/release_max_level_warn"]

optimism = [
    "reth-primitives/optimism",
    "reth-revm/optimism",
    "reth-interfaces/optimism",
    "reth-rpc/optimism",
    "reth-rpc-engine-api/optimism",
    "reth-provider/optimism",
    "reth-beacon-consensus/optimism",
    "reth-auto-seal-consensus/optimism",
    "reth-network/optimism",
    "reth-network-api/optimism",
    "reth-blockchain-tree/optimism",
    "reth-payload-builder/optimism",
    "reth-optimism-payload-builder/optimism",
    "dep:reth-node-optimism",
    "reth-node-core/optimism",
]

# no-op feature flag for switching between the `optimism` and default functionality in CI matrices
ethereum = []

# [[bin]]
# name = "reth"
# path = "src/main.rs"

# [[bin]]
# name = "op-reth"
# path = "src/optimism.rs"
# required-features = ["optimism"]

##------LUMIO-START-------
[[bin]]
name = "reth"
path = "src/optimism.rs"
required-features = ["optimism"]
##------LUMIO-END---------
