name: grafana

on:
  pull_request:
    paths: ["etc/**"]
  merge_group:
    paths: ["etc/**"]
  push:
    branches: [main]
    paths: ["etc/**"]

jobs:
  grafana:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Check dashboard JSON with jq
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq empty etc/grafana/dashboards/overview.json
